List wordArrayEng = [
  'Architect',
  'Chemist',
  'Egypt',
  'Map',
  'Norwegian',
  'Waitress',
  'Bedside',
  'Bookcase',
  'Dishwasher',
  'Garage',
  'Kitchen',
  'Mirror',
  'Action',
  'Historical Drama',
  'Playing Chess',
  'Rollerblading',
  'Science Fiction',
  'Scuba Diving',
  'Avalanche',
  'Drought',
  'Hill',
  'Hurricane',
  'Lake',
  'Waterfall',
  'Bald',
  'Cap',
  'Coat',
  'Curly',
  'Helpful',
  'Sneakers',
  'Announcement',
  'Passenger',
  'Plane',
  'Quiet',
  'Station',
  'Stressful',
  'Dead Tired',
  'Lighthouse',
  'Staircase',
  'Statue',
  'Temple',
  'Tomb',
  'Ankle',
  'Backpack',
  'Helmet',
  'Lab Coat',
  'Nosebleed',
  'Smoke Detector',
  'BookShop',
  'Bouquet',
  'Fancy Dress Party',
  'Graduation Party',
  'Harvest',
  'Toyshop',
  'Cartoon',
  'Cookery Programme',
  'Loudspeaker',
  'Quiz Show',
  'Remote Control',
  'Sports Programme',
].toList();

List wordArrayTr = [
  'Mimar',
  'Eczacı',
  'Mısır',
  'Harita',
  'Norveçli',
  'Bayan Garson',
  'Komidin',
  'Kitaplık',
  'Bulaşık Makinesi',
  'Garaj',
  'Mutfak',
  'Ayna',
  'Aksiyon',
  'Tarih Dizi',
  'Satranç Oynamak',
  'Paten',
  'Bilim Kurgu',
  'Dalış',
  'Çığ',
  'Kuraklık',
  'Tepe',
  'Kasırga',
  'Göl',
  'Şelale',
  'Kel',
  'Şapka',
  'Ceket',
  'Kıvırcık',
  'Yardım Sever',
  'Spor Ayakkabı',
  'Duyuru',
  'Yolcu',
  'Uçak',
  'Sessiz',
  'İstasyon',
  'Stresli',
  'Çok Yorgun',
  'Deniz Feneri',
  'Merdiven',
  'Heykel',
  'Tapınak',
  'Türbe',
  'Ayak Bileği',
  'Sırt Çantası',
  'Kask',
  'Laboratuvar Önlüğü',
  'Burun Kanaması',
  'Duman Dedektörü',
  'Kitapçı',
  'Buket',
  'Kostüm Partisi',
  'Mezuniyet Partisi',
  'Hasat',
  'Oyuncak Dükkanı',
  'Karikatür',
  'Asçılık Programı',
  'Hoparlör',
  'Bilgi Yarışması',
  'Uzaktan Kumanda',
  'Spor Programı',
].toList();

List imageArray = [
  "assets/0.jpg",
  "assets/1.jpg",
  "assets/2.jpg",
  "assets/3.jpg",
  "assets/4.jpg",
  "assets/5.jpg",
  "assets/6.jpg",
  "assets/7.jpg",
  "assets/8.jpg",
  "assets/9.jpg",
  "assets/10.jpg",
  "assets/11.jpg",
  "assets/12.jpg",
  "assets/13.jpg",
  "assets/14.jpg",
  "assets/15.jpg",
  "assets/16.jpg",
  "assets/17.jpg",
  "assets/18.jpg",
  "assets/19.jpg",
  "assets/20.jpg",
  "assets/21.jpg",
  "assets/22.jpg",
  "assets/23.jpg",
  "assets/24.jpg",
  "assets/25.jpg",
  "assets/26.jpg",
  "assets/27.jpg",
  "assets/28.jpg",
  "assets/29.jpg",
  "assets/30.jpg",
  "assets/31.jpg",
  "assets/32.jpg",
  "assets/33.jpg",
  "assets/34.jpg",
  "assets/35.jpg",
  "assets/36.jpg",
  "assets/37.jpg",
  "assets/38.jpg",
  "assets/39.jpg",
  "assets/40.jpg",
  "assets/41.jpg",
  "assets/42.jpg",
  "assets/43.jpg",
  "assets/44.jpg",
  "assets/45.jpg",
  "assets/46.jpg",
  "assets/47.jpg",
  "assets/48.jpg",
  "assets/49.jpg",
  "assets/50.jpg",
  "assets/51.jpg",
  "assets/52.jpg",
  "assets/53.jpg",
  "assets/54.jpg",
  "assets/55.jpg",
  "assets/56.jpg",
  "assets/57.jpg",
  "assets/58.jpg",
  "assets/59.jpg",
].toList();
