name: wordgame
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  syncfusion_localizations: ^18.4.44
  shared_preferences: ^2.0.4
  get: ^3.26.0
  flutter_launcher_icons: ^0.9.0
#  assets_audio_player: ^3.0.3
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/0.jpg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - assets/8.jpg
    - assets/9.jpg
    - assets/10.jpg
    - assets/11.jpg
    - assets/12.jpg
    - assets/13.jpg
    - assets/14.jpg
    - assets/15.jpg
    - assets/16.jpg
    - assets/17.jpg
    - assets/18.jpg
    - assets/19.jpg
    - assets/20.jpg
    - assets/21.jpg
    - assets/22.jpg
    - assets/23.jpg
    - assets/24.jpg
    - assets/25.jpg
    - assets/26.jpg
    - assets/27.jpg
    - assets/28.jpg
    - assets/29.jpg
    - assets/30.jpg
    - assets/31.jpg
    - assets/32.jpg
    - assets/33.jpg
    - assets/34.jpg
    - assets/35.jpg
    - assets/36.jpg
    - assets/37.jpg
    - assets/38.jpg
    - assets/39.jpg
    - assets/40.jpg
    - assets/41.jpg
    - assets/42.jpg
    - assets/43.jpg
    - assets/44.jpg
    - assets/45.jpg
    - assets/46.jpg
    - assets/47.jpg
    - assets/48.jpg
    - assets/49.jpg
    - assets/50.jpg
    - assets/51.jpg
    - assets/52.jpg
    - assets/53.jpg
    - assets/54.jpg
    - assets/55.jpg
    - assets/56.jpg
    - assets/57.jpg
    - assets/58.jpg
    - assets/59.jpg
    - assets/back/b1.jpg
    - assets/back/b2.jpg
    - assets/back/b3.jpg
    - assets/back/b4.jpg
    - assets/back/b5.jpg
    - assets/back/b6.jpg
    - assets/login.jpg
    - assets/musics/loginmusic.mp3
    - assets/musics/lose.mp3
    - assets/musics/win.mp3
    - assets/icon/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
